Добавил Ui компонент textField
SeanWoo/uCode pull request #47
Opened 2022-05-01 12:02 UTC by Rybik52

2022-05-02 15:17 UTC, SeanWoo commented on web/src/ui/TextField/index.js
> +    outline-offset: none !important;
!important убери везде

2022-05-03 13:13 UTC, Rybik52 commented on web/src/ui/TextField/index.js
> +    outline-offset: none !important;
Убрал

2022-05-03 15:26 UTC, SeanWoo commented on web/src/pages/main/index.js
> +    </div>
PageWrapper вынес на уровень ниже, он на то и wrapper чтоб обернуть все остальное на странице, а вообще лучше сделать компонент Layout который заменит PageWrapper и рендерить его нужно будет в App.js

2022-05-03 15:26 UTC, SeanWoo commented on web/src/pages/main/index.js
> +import { TextField } from '../../ui/TextField';
Убери относительные импорты

2022-05-03 15:27 UTC, SeanWoo commented
В ветке конфликты, помержи с девом

2022-05-12 19:16 UTC, SeanWoo commented on web/src/pages/main/index.js
> +import { TextWrapper } from '../../ui/TextField/index';
поправь импорты

2022-05-12 19:17 UTC, SeanWoo commented on web/src/components/layout/index.js
> +import { LayoutWrapper } from './layout';
файл со стилями называй styles.js

2022-05-12 19:18 UTC, SeanWoo commented on web/src/components/mainWrapper/mainWrapper.js
>    min-height: 100vh;
зачем это?

2022-05-14 18:40 UTC, Rybik52 commented
а вот так всё выглядит
<img width="349" alt="image" src="https://user-images.githubusercontent.com/74355761/168444409-88b15ca3-ad3b-4c8a-9e46-dc2c3141df8b.png">
<img width="339" alt="image" src="https://user-images.githubusercontent.com/74355761/168444427-3a1549de-46c6-460e-8242-721131063125.png">
<img width="325" alt="image" src="https://user-images.githubusercontent.com/74355761/168444434-d11f1f86-9507-4ad1-a28d-b71f34381977.png">

2022-05-14 18:46 UTC, Rybik52 commented on web/src/components/mainWrapper/mainWrapper.js
>    min-height: 100vh;
Изменил название компонента для семантики посчитал что так понятнее

2022-05-14 18:48 UTC, Rybik52 commented on web/src/pages/main/index.js
> +import { TextWrapper } from '../../ui/TextField/index';
Поправил

2022-05-14 18:48 UTC, Rybik52 commented on web/src/components/layout/index.js
> +import { LayoutWrapper } from './layout';
Переименовал

2022-05-15 14:26 UTC, SeanWoo commented on web/src/App.js
> +import { MainWrapper } from './components/mainWrapper/mainWrapper';
mainWrapper.js -> index.js

2022-05-15 14:27 UTC, SeanWoo requested changes

2022-05-15 14:27 UTC, SeanWoo commented on web/src/pages/main/index.js
> +import { TextField, TextWrapper } from '../../ui/TextField/index';
убери относительный импорт

2022-05-15 14:44 UTC, SeanWoo commented on web/src/components/layout/index.js
> +import { AppRouter } from '../../pages/AppRouter';
убери относительные импорты

2022-05-15 20:34 UTC, Rybik52 commented on web/src/pages/main/index.js
> +import { TextField, TextWrapper } from '../../ui/TextField/index';
Убрал

2022-05-15 20:34 UTC, Rybik52 commented on web/src/components/layout/index.js
> +import { AppRouter } from '../../pages/AppRouter';
убрал

2022-05-16 15:48 UTC, SeanWoo approved these changes

2022-05-16 15:48 UTC, merged