UI checkbox created
SeanWoo/uCode pull request #51
Opened 2022-05-14 11:35 UTC by midas-png

Создал чекбокс по макету с фигма с size маппером (small: 16px, medium: 20px, large: 26px) и clicked маппером.
В domain/theme.js добавил цвета border'а и размеры для чекбокса.
![image](https://user-images.githubusercontent.com/78198187/168423907-b55b3bb2-2667-4747-8bf0-844fda109cea.png)

2022-05-14 14:58 UTC, SeanWoo commented
А где отступы между текстом и чекбоксом?

2022-05-14 15:00 UTC, SeanWoo requested changes

2022-05-14 15:00 UTC, SeanWoo commented on web/src/pages/main/index.jsx
> +      </label>
добавь лейбл во внутрь компонента чекбокса

2022-05-15 10:40 UTC, midas-png commented
Добавил текст в компонент чекбокса и сделал отступ
![image](https://user-images.githubusercontent.com/78198187/168468653-d6ff0d5d-7859-415b-8b73-1293eb5e2a5b.png)

2022-05-15 14:14 UTC, SeanWoo commented on web/src/ui/Checkbox/index.js
> +      <span>{text}</span>
утебя span будет рендерится всегда, сделай проверку на наличие текста в text пропсе

2022-05-15 14:29 UTC, SeanWoo commented on web/src/ui/Checkbox/index.js
> +      {text ? <span>{text}</span> : null}
```suggestion
      {text && <span>{text}</span>}
```

2022-05-15 14:32 UTC, SeanWoo approved these changes

2022-05-15 14:32 UTC, merged