Feature/sidebar fix
SeanWoo/uCode pull request #54
Opened 2022-05-15 14:39 UTC by Rybik52

### Исправил родительскую ветку!

При нажатии на кнопку корзина 
<img width="87" alt="image" src="https://user-images.githubusercontent.com/74355761/168444033-441572c3-cafd-4247-ace6-4fee4b04fff3.png">
затемняется задний фон и выезжает корзина
<img width="1080" alt="image" src="https://user-images.githubusercontent.com/74355761/168443923-e826fd75-291c-4746-8352-237d36908fb1.png">
для того чтобы закрыть можно нажать на затемненный бг или же на кнопку с крестиком 
Все ховеры: 
<img width="42" alt="image" src="https://user-images.githubusercontent.com/74355761/168444084-331cf361-6508-45a7-981c-c48f637e13e9.png">
<img width="31" alt="image" src="https://user-images.githubusercontent.com/74355761/168444096-d76346a1-dc32-47c6-892a-be317f0b911a.png">
<img width="295" alt="image" src="https://user-images.githubusercontent.com/74355761/168444174-69951f30-96f4-4770-a4db-7b85ef3ec637.png">
<img width="298" alt="image" src="https://user-images.githubusercontent.com/74355761/168444182-7b7176ca-053e-4f0d-973f-7d9c0490ee39.png">

2022-05-15 14:54 UTC, SeanWoo commented on web/src/ui/Navbar/Sidebar/sidebar.js
> +import noImg from '../../../assets/no-image.png';
еще один

2022-05-15 14:55 UTC, SeanWoo commented on web/src/ui/Navbar/Topbar/index.js
>  import { useAuth } from '../../../domain/hooks/useAuth';
импорты поправь

2022-05-15 20:59 UTC, Rybik52 commented on web/src/ui/Navbar/Sidebar/sidebar.js
> +import noImg from '../../../assets/no-image.png';
Исправил

2022-05-15 21:00 UTC, Rybik52 commented on web/src/ui/Navbar/Topbar/index.js
>  import { useAuth } from '../../../domain/hooks/useAuth';
Исправил

2022-05-19 18:26 UTC, SeanWoo requested changes

2022-05-19 18:26 UTC, SeanWoo commented on web/src/ui/Navbar/Sidebar/index.js
> +  const CardsData = [
с маленькой буквы

2022-05-19 18:26 UTC, SeanWoo commented on web/src/ui/Navbar/Sidebar/index.js
> +      src: require('assets/default.png'),
создай Icons компонент который будет состоять из компонентов иконок, а иконки импортируй через import как реакт компонент

2022-05-19 18:26 UTC, SeanWoo commented on web/src/ui/Navbar/Sidebar/index.js
> +        style={!isOpen ? { display: 'none' } : null}
вынеси

2022-05-19 18:26 UTC, SeanWoo commented on web/src/ui/Navbar/Sidebar/index.js
> +        onClick={() => setIsOpen(!isOpen)}
создай хук useToggle который будет при вызове метода сам менять состояние на обратное

2022-05-19 18:26 UTC, SeanWoo commented on web/src/ui/Navbar/Sidebar/index.js
> +        style={!isOpen ? { transform: 'translate(100%)' } : null}>
Вынеси

2022-05-19 18:26 UTC, SeanWoo commented on web/src/ui/Navbar/Sidebar/index.js
> +          <SidebarExitBtn onClick={() => setIsOpen(!isOpen)}>✖</SidebarExitBtn>
в хук, и вынеси

2022-05-19 18:26 UTC, SeanWoo commented on web/src/ui/Navbar/Sidebar/index.js
> +          <SidebarCardData CardsData={CardsData} />
пропсы с маленькой

2022-05-19 18:26 UTC, SeanWoo commented on web/src/ui/Navbar/Sidebar/style.js
> +export const SidebarBG = styled.div`
дай нормальное название, желательно все компоненты из styled-components начинать называть со Styled (example StyledContainer)

2022-05-19 18:26 UTC, SeanWoo commented on web/src/ui/Navbar/Sidebar/style.js
> +export const SidebarExitBtn = styled.button`
нормальное название без сокращений, указывать везде Sidebar не нужно, так как эти стили не должны где-то еще использоваться

2022-05-19 18:26 UTC, SeanWoo commented on web/src/ui/Navbar/Sidebar/style.js
> +  // widht: 100%;
удалить

2022-05-19 18:26 UTC, SeanWoo commented on web/src/ui/Navbar/Sidebar/style.js
> +  background: url(${({ src }) => src || require('assets/no-image.png')});
убрать require, переделать лого

2022-05-19 18:26 UTC, SeanWoo commented on web/src/ui/Navbar/Sidebar/style.js
> +  width: 77%;
откуда такие цифры?

2022-05-19 18:26 UTC, SeanWoo commented on web/src/ui/Navbar/Sidebar/style.js
> +  background: #000;
возми из темы цвет

2022-05-19 18:26 UTC, SeanWoo commented on web/src/ui/Navbar/Sidebar/style.js
> +  background-color: white;
возми из темы

2022-05-19 18:26 UTC, SeanWoo commented on web/src/ui/Navbar/Sidebar/style.js
> +  width: 65%;
откуда такие цифры?

2022-05-19 18:26 UTC, SeanWoo commented on web/src/ui/Navbar/Topbar/index.js
> +              onClick={() => setSidebarOpen(!sidebarOpen)}>
замени потом хуком

2022-05-19 18:26 UTC, SeanWoo commented on web/src/ui/Navbar/Topbar/index.js
>            ) : null}
убери null

2022-05-21 15:41 UTC, Rybik52 commented on web/src/ui/Navbar/Sidebar/index.js
> +        onClick={() => setIsOpen(!isOpen)}
Готово

2022-05-21 15:42 UTC, Rybik52 commented on web/src/ui/Navbar/Sidebar/style.js
> +  width: 65%;
Изменил на пиксели, если честно не очень понимаю как лучше сделать(

2022-05-21 15:46 UTC, SeanWoo commented on web/src/domain/hooks/useToggle.js
> +export const useToggle = (startValue) => {
startValue -> initValue

2022-05-21 15:46 UTC, SeanWoo commented on web/src/domain/hooks/useToggle.js
> +    setValue(!value);
```suggestion
    setValue((prev) => !prev);
```

2022-05-21 16:32 UTC, Rybik52 commented on web/src/ui/Navbar/Topbar/index.js
>            ) : null}
Это не моё а Яна

2022-05-21 16:41 UTC, Rybik52 commented on web/src/ui/Navbar/Topbar/index.js
>            ) : null}
<img width="1080" alt="image" src="https://user-images.githubusercontent.com/74355761/169661128-3e6c5a52-d1cc-4362-bdee-82ad8ccf57d1.png">

2022-05-21 18:56 UTC, SeanWoo commented on web/src/ui/Navbar/Topbar/index.js
>            ) : null}
И что? Как то, что ты скинул этот косяк на Яна, помогло команде и качеству кода?

2022-05-21 19:00 UTC, Rybik52 commented on web/src/ui/Navbar/Topbar/index.js
>            ) : null}
Да не подумал, соре Ян и Вадим, сейчас начну исправляться)

2022-05-25 12:26 UTC, SeanWoo commented on web/src/http/index.js
> +// eslint-disable-next-line import/no-unresolved
и выше `/* eslint-disable max-len */` тоже

2022-05-25 12:28 UTC, SeanWoo commented on web/src/ui/Navbar/Sidebar/style.jsx
> +  transform: ${({ open }) => (!open ? 'translate(100%)' : null)};
Тоже что и выше

2022-05-25 12:29 UTC, SeanWoo commented on web/src/ui/Navbar/Sidebar/style.jsx
> +export const BtnWrapper = styled.span`
Дай нормальное название: ButtonWrapper

2022-05-25 12:30 UTC, SeanWoo commented on web/src/ui/Navbar/Sidebar/style.jsx
> +export const SidebarCardPrice = styled.span`
Убери везде Sidebar, к компонентам styled-components добавляй в начале слово Styled.
То что это компоненты сайдбара и так понятно, оно лежит рядом с компонентом где используется, и больше нигде их нельзя использовать

2022-05-25 12:31 UTC, SeanWoo commented on web/src/ui/Navbar/Topbar/index.js
>  import { Button, Title, TextField } from '../../index';
поправь импорт

2022-05-25 12:31 UTC, SeanWoo commented on web/src/ui/Navbar/Topbar/index.js
> +import { Sidebar } from '../Sidebar';
сделай абсолютный путь

2022-05-25 19:18 UTC, Rybik52 commented on web/src/http/index.js
> +// eslint-disable-next-line import/no-unresolved
<img width="1080" alt="image" src="https://user-images.githubusercontent.com/74355761/170350621-a99a161a-f774-4bc3-b5f5-5fbbd1138511.png">
А как с этим быть?

2022-05-28 17:03 UTC, SeanWoo commented on web/src/http/index.js
> +// eslint-disable-next-line import/no-unresolved
этот токен можешь вообще убрать щас, его нужно с сервера тащить, в локал сторейдж сохранять и оттуда тянуть

2022-05-30 18:03 UTC, SeanWoo requested changes

2022-05-30 18:03 UTC, SeanWoo commented on web/src/ui/Navbar/Topbar/index.js
>    const [loginRole, setLoginRole] = useState('STUDENT');
замени на `number` и сделай `Enum`

2022-05-30 18:32 UTC, merged