Public routes and basic page components created
SeanWoo/uCode pull request #6
Opened 2022-02-18 17:32 UTC by midas-png

Создал 9 публичных роутов, создал пустые компоненты-страницы под каждый роут и связал их

2022-02-19 23:02 UTC, SeanWoo commented on web/src/pages/publicRoutes.js
> +import TermsPage from './terms';
Чтоб такого не было, создаем в папке pages index.js файл и экспортируем в нем все компоненты этой папки, по аналогии делаем и с другими папками

2022-02-21 12:38 UTC, midas-png commented
Сделал. Единственное в publicRoutes.js не получилось убрать импорты JSX тегов, т.к в react-router-dom с 6v в element нужно передавать сразу JSX Тег

2022-02-21 16:29 UTC, SeanWoo requested changes

2022-02-21 16:29 UTC, SeanWoo commented on web/src/pages/index.js
> +};
просто `export * from '.routeConsts';`

2022-02-21 16:29 UTC, SeanWoo commented on web/src/pages/publicRoutes.js
> +import { TermsPage } from './terms';
в папке pages создаем файл index.js и экспортируем оттуда все страницы, а отсюда далее импортируем одним импортом перечислив страницы

2022-02-21 19:24 UTC, midas-png commented on web/src/pages/publicRoutes.js
> +import { TermsPage } from './terms';
в папке publicRoutes.js ничего не менять? Я не смогу импортировать JSX теги и передать их в Element, только если откатить react-router-dom на v5

2022-02-21 20:34 UTC, midas-png commented on web/src/pages/publicRoutes.js
> +import { TermsPage } from './terms';
Понял

2022-02-25 09:21 UTC, SeanWoo approved these changes

2022-02-25 09:21 UTC, merged